const prompt = require("prompt-sync")()

let salarioPh = Number(prompt("digite seu salario "))
let horasPM = Number(prompt("digite suas horas trabalhadas "))
let salarioB = (salarioPh * horasPM)
console.log(`seu salario bruto é ${salarioB}`)
let IR = (salarioB * 0.11)
console.log(`desconto do imposto de renda ${IR}`)
let inss = (salarioB * 0.08)
console.log(`desconto do INSS ${inss}`)
let sindicato = (salarioB * 0.05)
console.log(`desconto do sindicato ${sindicato}`)
let salarioL = (salarioB - IR - inss - sindicato)
console.log(`seu salario liquido é ${salarioL}`)